version: "3"
services:

    postgres:
        image: postgres:latest
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: postgres
        ports:
            - '5432:5432'
        networks:
            - app

    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - '1025:1025'
            - '8025:8025'
        networks:
            - app


volumes:
    postgres_data:

networks:
    app:

